#server:
#  port: 8080
#jwt:
#  secret: dGVhbVdhZ21pTGV0c1Nlb3Vs
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties: #
      hibernate: #
        dialect: org.hibernate.dialect.MySQL57Dialect #
        storage_engine: innodb #
  session:
    timeout: 600
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
  datasource: #
    url: jdbc:mysql://localhost:3306/lets_seoul?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false #
    #    url: jdbc:mysql://15.165.91.245:3306/lets_seoul?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false #
    username: letsseoul #
    password: FPTCM!tjdnf2ELQL#tjqj4 #
    driver-class-name: com.mysql.cj.jdbc.Driver #
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 463351822248-jf0m97mt90o6u7r45urph02osc8t1mss.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: gSug674SZq8jlLVEM4JG
            client-secret: cQhM3dDfOE
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - nickname
              - profile_image
            client-name: Naver
          kakao:
            client-authentication-method: POST
            client-id: ca0054307db296996f1945e19583c627
            client-secret: jKCRWC08YqpY9JVg7cgjOArIGeiYpLfP
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  auth:
    token:
      secret-key: VGVhbVdhZ21pQXV0aFRva2VuU2VjcmV0S2V5QmFzZTY0RW5jb2RpbmdGb3JtYXR0ZWRURUFNV0FHTUlBVVRIVE9LRU5TRUNSRVRLRVlCQVNFNjRFTkNPRElOR0ZPUk1BVFRFRA==
      refresh-cookie-key: VGVhbVdhZ21pQXV0aFRva2VuUmVmcmVzaENvb2tpZUtleUJhc2U2NEVuY29kaW5nRm9ybWF0dGVkVEVBTVdBR01JQVVUSFRPS0VOUkVGUkVTSENPT0tJRUtFWUJBU0U2NEVOQ09ESU5HRk9STUFUVEVE

#          kakao:
#            client-id: ca0054307db296996f1945e19583c627
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#                        redirect-uri: https://letsseoul.com/login/oauth2/code/kakao
#            authorization-grant-type: authorization_code
#            client-authentication-method: POST
#            client-name: Kakao
#            scope:
#              - profile_nickname
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id

#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#  profiles:
#    include: oauth,db
#  session:
#    store-type: jdbc