spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create #
    properties: #
      hibernate: #
        dialect: org.hibernate.dialect.MySQL57Dialect #
        storage_engine: innodb #
  session:
    timeout: 600
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
  datasource: #
    url: jdbc:mysql://localhost:3306/lets_seoul?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false #
    #    url: jdbc:mysql://15.165.91.245:3306/lets_seoul?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false #
    username: letsseoul #
    password: FPTCM!tjdnf2ELQL#tjqj4 #
    driver-class-name: com.mysql.cj.jdbc.Driver #
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 463351822248-jf0m97mt90o6u7r45urph02osc8t1mss.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: gSug674SZq8jlLVEM4JG
            client-secret: cQhM3dDfOE
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - nickname
              - profile_image
            client-name: Naver
          kakao:
            client-authentication-method: POST
            client-id: ca0054307db296996f1945e19583c627
            client-secret: jKCRWC08YqpY9JVg7cgjOArIGeiYpLfP
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id